// Objective-C API for talking to yho.io/etcd Go package.
//   gobind -lang=objc yho.io/etcd
//
// File is generated by gobind. Do not edit.

#ifndef __Etcd_H__
#define __Etcd_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class EtcdKVClient;
@class EtcdObjects;

@interface EtcdKVClient : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init:(NSString* _Nullable)endpoints username:(NSString* _Nullable)username password:(NSString* _Nullable)password cert:(NSString* _Nullable)cert certKey:(NSString* _Nullable)certKey requestTimeout:(long)requestTimeout dialTimeout:(long)dialTimeout dialKeepAliveTime:(long)dialKeepAliveTime dialKeepAliveTimeout:(long)dialKeepAliveTimeout autoSyncInterval:(long)autoSyncInterval;
- (NSData* _Nullable)all:(NSError* _Nullable* _Nullable)error;
- (BOOL)authEnable:(BOOL)enable error:(NSError* _Nullable* _Nullable)error;
- (BOOL)authGrant:(NSString* _Nullable)user role:(NSString* _Nullable)role error:(NSError* _Nullable* _Nullable)error;
- (NSData* _Nullable)children:(NSError* _Nullable* _Nullable)error;
- (BOOL)close:(NSError* _Nullable* _Nullable)error;
- (NSData* _Nullable)clusterStatus:(NSError* _Nullable* _Nullable)error;
- (BOOL)delete:(NSString* _Nullable)key error:(NSError* _Nullable* _Nullable)error;
- (BOOL)deleteAll:(NSError* _Nullable* _Nullable)error;
- (BOOL)deletePrefix:(NSString* _Nullable)prefix error:(NSError* _Nullable* _Nullable)error;
- (BOOL)deleteRole:(NSString* _Nullable)role error:(NSError* _Nullable* _Nullable)error;
- (BOOL)deleteUser:(NSString* _Nullable)user error:(NSError* _Nullable* _Nullable)error;
- (BOOL)endPointHealth:(NSError* _Nullable* _Nullable)error;
- (NSData* _Nullable)get:(NSString* _Nullable)key error:(NSError* _Nullable* _Nullable)error;
- (NSData* _Nullable)getPrefix:(NSString* _Nullable)prefix error:(NSError* _Nullable* _Nullable)error;
- (BOOL)grant:(long)ttl ret0_:(long* _Nullable)ret0_ error:(NSError* _Nullable* _Nullable)error;
- (BOOL)memberAdd:(NSString* _Nullable)endpoint error:(NSError* _Nullable* _Nullable)error;
- (NSData* _Nullable)memberList:(NSError* _Nullable* _Nullable)error;
- (BOOL)memberRemove:(long)id_ error:(NSError* _Nullable* _Nullable)error;
- (BOOL)memberUpdate:(long)id_ peerUrl:(NSString* _Nullable)peerUrl error:(NSError* _Nullable* _Nullable)error;
- (BOOL)metrics:(NSString* _Nullable)endpoint error:(NSError* _Nullable* _Nullable)error;
- (BOOL)permission:(NSString* _Nullable)role key:(NSString* _Nullable)key end:(NSString* _Nullable)end error:(NSError* _Nullable* _Nullable)error;
- (BOOL)put:(NSString* _Nullable)key value:(NSString* _Nullable)value error:(NSError* _Nullable* _Nullable)error;
- (BOOL)putKeyWithAliveOnce:(NSString* _Nullable)key value:(NSString* _Nullable)value leaseid:(long)leaseid error:(NSError* _Nullable* _Nullable)error;
- (BOOL)putKeyWithLease:(NSString* _Nullable)key value:(NSString* _Nullable)value ttl:(long)ttl error:(NSError* _Nullable* _Nullable)error;
- (BOOL)revoke:(long)leaseid error:(NSError* _Nullable* _Nullable)error;
- (BOOL)roleAdd:(NSString* _Nullable)role error:(NSError* _Nullable* _Nullable)error;
- (EtcdObjects* _Nullable)roles:(NSError* _Nullable* _Nullable)error;
- (NSData* _Nullable)sortPrefix:(long)des prefix:(NSString* _Nullable)prefix error:(NSError* _Nullable* _Nullable)error;
- (NSData* _Nullable)status:(NSString* _Nullable)endpoint error:(NSError* _Nullable* _Nullable)error;
- (BOOL)userAdd:(NSString* _Nullable)user password:(NSString* _Nullable)password error:(NSError* _Nullable* _Nullable)error;
- (EtcdObjects* _Nullable)users:(NSError* _Nullable* _Nullable)error;
@end

@interface EtcdObjects : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@end

FOUNDATION_EXPORT EtcdKVClient* _Nullable EtcdNewKVClient(NSString* _Nullable endpoints, NSString* _Nullable username, NSString* _Nullable password, NSString* _Nullable cert, NSString* _Nullable certKey, long requestTimeout, long dialTimeout, long dialKeepAliveTime, long dialKeepAliveTimeout, long autoSyncInterval, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT EtcdKVClient* _Nullable EtcdNewMock(void);

#endif
