# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'etcdWP (iOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Google-Mobile-Ads-SDK'
  pod 'WCDB.swift'
  # Pods for etcdWP (iOS)

end

target 'etcdWP (macOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for etcdWP (macOS)

end
