
// Objective-C API for talking to the following Go packages
//
//	yho.io/etcd
//
// File is generated by gomobile bind. Do not edit.
#ifndef __MacosEtcd_FRAMEWORK_H__
#define __MacosEtcd_FRAMEWORK_H__

#include "Etcd.objc.h"
#include "Universe.objc.h"

#endif
